export type Color = 
    "rose" | "red" | "orange" | "amber" | "yellow" | "lime" | "green" | "emerald" | "teal" | "cyan" | "blue" | "indigo" | "violet" | "purple" | "fuchsia" | "pink" | "gray" | "sub" | "none" |
    "white" | "black" |
    "primary" | "secondary" | "accent" |
    "error" | "warning" | "success" | "info";
export type ButtonColorStyleType = "full" | "light" | "outline" | "ghost";
export type ColorStyleType = "base" | "baseHover" | "baseChecked" | "text" | "hover" | "muted" | "subtle" | "mutedHover" | "border" | "borderHover" | "textHover" | "subtleHover" | "from" | "to" | "via" | "fromHover" | "toHover" | "viaHover";

export const colorStyles = [
    "rose", "red", "orange", "amber", "yellow", "lime", "green", "emerald", "teal", "cyan", "blue", "indigo", "violet", "purple", "fuchsia", "pink", "gray", "sub", "none",
    "white", "black",
    "primary", "secondary", "accent",
    "error", "warning", "success", "info"
] as const satisfies Color[];
export const colorStyleTypes = [
    "base", "baseHover", "baseChecked", "text", "hover", "muted", "subtle", "mutedHover", "border", "borderHover", "textHover", "subtleHover", "from", "to", "via", "fromHover", "toHover", "viaHover"
] as const satisfies ColorStyleType[];

export interface Gradient {
    from: Color;
    to: Color;
    via?: Color;
    deg?: number;
}

export type ColorType = Color | Gradient;

export const colorStyleParts: Record<Color, Record<ColorStyleType, string>> = {
    rose: {
        base: "bg-rose-600",
        baseHover: "hover:bg-rose-600",
        baseChecked: "checked:bg-rose-600",
        text: "text-rose-600",
        textHover: "hover:text-rose-700",
        hover: "hover:bg-rose-700",
        muted: "bg-rose-600/35",
        mutedHover: "hover:bg-rose-700/35",
        subtle: "bg-rose-600/10",
        subtleHover: "hover:bg-rose-600/10",
        border: "border-rose-600",
        borderHover: "hover:border-rose-700",
        from: "from-rose-600",
        to: "to-rose-600",
        via: "via-rose-600",
        fromHover: "hover:from-rose-700",
        toHover: "hover:to-rose-700",
        viaHover: "hover:via-rose-700"
    },
    red: {
        base: "bg-red-600",
        baseHover: "hover:bg-red-600",
        baseChecked: "checked:bg-red-600",
        text: "text-red-600",
        textHover: "hover:text-red-700",
        hover: "hover:bg-red-700",
        muted: "bg-red-600/35",
        mutedHover: "hover:bg-red-700/35",
        subtle: "bg-red-600/10",
        subtleHover: "hover:bg-red-600/10",
        border: "border-red-600",
        borderHover: "hover:border-red-700",
        from: "from-red-600",
        to: "to-red-600",
        via: "via-red-600",
        fromHover: "hover:from-red-700",
        toHover: "hover:to-red-700",
        viaHover: "hover:via-red-700"
    },
    orange: {
        base: "bg-orange-600",
        baseHover: "hover:bg-orange-600",
        baseChecked: "checked:bg-orange-600",
        text: "text-orange-600",
        textHover: "hover:text-orange-700",
        hover: "hover:bg-orange-700",
        muted: "bg-orange-600/35",
        mutedHover: "hover:bg-orange-700/35",
        subtle: "bg-orange-600/10",
        subtleHover: "hover:bg-orange-600/10",
        border: "border-orange-600",
        borderHover: "hover:border-orange-700",
        from: "from-orange-600",
        to: "to-orange-600",
        via: "via-orange-600",
        fromHover: "hover:from-orange-700",
        toHover: "hover:to-orange-700",
        viaHover: "hover:via-orange-700"
    },
    amber: {
        base: "bg-amber-600",
        baseHover: "hover:bg-amber-600",
        baseChecked: "checked:bg-amber-600",
        text: "text-amber-600",
        textHover: "hover:text-amber-700",
        hover: "hover:bg-amber-700",
        muted: "bg-amber-600/35",
        mutedHover: "hover:bg-amber-700/35",
        subtle: "bg-amber-600/10",
        subtleHover: "hover:bg-amber-600/10",
        border: "border-amber-600",
        borderHover: "hover:border-amber-700",
        from: "from-amber-600",
        to: "to-amber-600",
        via: "via-amber-600",
        fromHover: "hover:from-amber-700",
        toHover: "hover:to-amber-700",
        viaHover: "hover:via-amber-700"
    },
    yellow: {
        base: "bg-yellow-600",
        baseHover: "hover:bg-yellow-600",
        baseChecked: "checked:bg-yellow-600",
        text: "text-yellow-600",
        textHover: "hover:text-yellow-700",
        hover: "hover:bg-yellow-700",
        muted: "bg-yellow-600/35",
        mutedHover: "hover:bg-yellow-700/35",
        subtle: "bg-yellow-600/10",
        subtleHover: "hover:bg-yellow-600/10",
        border: "border-yellow-600",
        borderHover: "hover:border-yellow-700",
        from: "from-yellow-600",
        to: "to-yellow-600",
        via: "via-yellow-600",
        fromHover: "hover:from-yellow-700",
        toHover: "hover:to-yellow-700",
        viaHover: "hover:via-yellow-700"
    },
    lime: {
        base: "bg-lime-600",
        baseHover: "hover:bg-lime-600",
        baseChecked: "checked:bg-lime-600",
        text: "text-lime-600",
        textHover: "hover:text-lime-700",
        hover: "hover:bg-lime-700",
        muted: "bg-lime-600/35",
        mutedHover: "hover:bg-lime-700/35",
        subtle: "bg-lime-600/10",
        subtleHover: "hover:bg-lime-600/10",
        border: "border-lime-600",
        borderHover: "hover:border-lime-700",
        from: "from-lime-600",
        to: "to-lime-600",
        via: "via-lime-600",
        fromHover: "hover:from-lime-700",
        toHover: "hover:to-lime-700",
        viaHover: "hover:via-lime-700"
    },
    green: {
        base: "bg-green-600",
        baseHover: "hover:bg-green-600",
        baseChecked: "checked:bg-green-600",
        text: "text-green-600",
        textHover: "hover:text-green-700",
        hover: "hover:bg-green-700",
        muted: "bg-green-600/35",
        mutedHover: "hover:bg-green-700/35",
        subtle: "bg-green-600/10",
        subtleHover: "hover:bg-green-600/10",
        border: "border-green-600",
        borderHover: "hover:border-green-700",
        from: "from-green-600",
        to: "to-green-600",
        via: "via-green-600",
        fromHover: "hover:from-green-700",
        toHover: "hover:to-green-700",
        viaHover: "hover:via-green-700"
    },
    emerald: {
        base: "bg-emerald-600",
        baseHover: "hover:bg-emerald-600",
        baseChecked: "checked:bg-emerald-600",
        text: "text-emerald-600",
        textHover: "hover:text-emerald-700",
        hover: "hover:bg-emerald-700",
        muted: "bg-emerald-600/35",
        mutedHover: "hover:bg-emerald-700/35",
        subtle: "bg-emerald-600/10",
        subtleHover: "hover:bg-emerald-600/10",
        border: "border-emerald-600",
        borderHover: "hover:border-emerald-700",
        from: "from-emerald-600",
        to: "to-emerald-600",
        via: "via-emerald-600",
        fromHover: "hover:from-emerald-700",
        toHover: "hover:to-emerald-700",
        viaHover: "hover:via-emerald-700"
    },
    teal: {
        base: "bg-teal-600",
        baseHover: "hover:bg-teal-600",
        baseChecked: "checked:bg-teal-600",
        text: "text-teal-600",
        textHover: "hover:text-teal-700",
        hover: "hover:bg-teal-700",
        muted: "bg-teal-600/35",
        mutedHover: "hover:bg-teal-700/35",
        subtle: "bg-teal-600/10",
        subtleHover: "hover:bg-teal-600/10",
        border: "border-teal-600",
        borderHover: "hover:border-teal-700",
        from: "from-teal-600",
        to: "to-teal-600",
        via: "via-teal-600",
        fromHover: "hover:from-teal-700",
        toHover: "hover:to-teal-700",
        viaHover: "hover:via-teal-700"
    },
    cyan: {
        base: "bg-cyan-600",
        baseHover: "hover:bg-cyan-600",
        baseChecked: "checked:bg-cyan-600",
        text: "text-cyan-600",
        textHover: "hover:text-cyan-700",
        hover: "hover:bg-cyan-700",
        muted: "bg-cyan-600/35",
        mutedHover: "hover:bg-cyan-700/35",
        subtle: "bg-cyan-600/10",
        subtleHover: "hover:bg-cyan-600/10",
        border: "border-cyan-600",
        borderHover: "hover:border-cyan-700",
        from: "from-cyan-600",
        to: "to-cyan-600",
        via: "via-cyan-600",
        fromHover: "hover:from-cyan-700",
        toHover: "hover:to-cyan-700",
        viaHover: "hover:via-cyan-700"
    },
    blue: {
        base: "bg-blue-600",
        baseHover: "hover:bg-blue-600",
        baseChecked: "checked:bg-blue-600",
        text: "text-blue-600",
        textHover: "hover:text-blue-700",
        hover: "hover:bg-blue-700",
        muted: "bg-blue-600/35",
        mutedHover: "hover:bg-blue-700/35",
        subtle: "bg-blue-600/10",
        subtleHover: "hover:bg-blue-600/10",
        border: "border-blue-600",
        borderHover: "hover:border-blue-700",
        from: "from-blue-600",
        to: "to-blue-600",
        via: "via-blue-600",
        fromHover: "hover:from-blue-700",
        toHover: "hover:to-blue-700",
        viaHover: "hover:via-blue-700"
    },
    indigo: {
        base: "bg-indigo-600",
        baseHover: "hover:bg-indigo-600",
        baseChecked: "checked:bg-indigo-600",
        text: "text-indigo-600",
        textHover: "hover:text-indigo-700",
        hover: "hover:bg-indigo-700",
        muted: "bg-indigo-600/35",
        mutedHover: "hover:bg-indigo-700/35",
        subtle: "bg-indigo-600/10",
        subtleHover: "hover:bg-indigo-600/10",
        border: "border-indigo-600",
        borderHover: "hover:border-indigo-700",
        from: "from-indigo-600",
        to: "to-indigo-600",
        via: "via-indigo-600",
        fromHover: "hover:from-indigo-700",
        toHover: "hover:to-indigo-700",
        viaHover: "hover:via-indigo-700"
    },
    violet: {
        base: "bg-violet-600",
        baseHover: "hover:bg-violet-600",
        baseChecked: "checked:bg-violet-600",
        text: "text-violet-600",
        textHover: "hover:text-violet-700",
        hover: "hover:bg-violet-700",
        muted: "bg-violet-600/35",
        mutedHover: "hover:bg-violet-700/35",
        subtle: "bg-violet-600/10",
        subtleHover: "hover:bg-violet-600/10",
        border: "border-violet-600",
        borderHover: "hover:border-violet-700",
        from: "from-violet-600",
        to: "to-violet-600",
        via: "via-violet-600",
        fromHover: "hover:from-violet-700",
        toHover: "hover:to-violet-700",
        viaHover: "hover:via-violet-700"
    },
    purple: {
        base: "bg-purple-600",
        baseHover: "hover:bg-purple-600",
        baseChecked: "checked:bg-purple-600",
        text: "text-purple-600",
        textHover: "hover:text-purple-700",
        hover: "hover:bg-purple-700",
        muted: "bg-purple-600/35",
        mutedHover: "hover:bg-purple-700/35",
        subtle: "bg-purple-600/10",
        subtleHover: "hover:bg-purple-600/10",
        border: "border-purple-600",
        borderHover: "hover:border-purple-700",
        from: "from-purple-600",
        to: "to-purple-600",
        via: "via-purple-600",
        fromHover: "hover:from-purple-700",
        toHover: "hover:to-purple-700",
        viaHover: "hover:via-purple-700"
    },
    pink: {
        base: "bg-pink-600",
        baseHover: "hover:bg-pink-600",
        baseChecked: "checked:bg-pink-600",
        text: "text-pink-600",
        textHover: "hover:text-pink-700",
        hover: "hover:bg-pink-700",
        muted: "bg-pink-600/35",
        mutedHover: "hover:bg-pink-700/35",
        subtle: "bg-pink-600/10",
        subtleHover: "hover:bg-pink-600/10",
        border: "border-pink-600",
        borderHover: "hover:border-pink-700",
        from: "from-pink-600",
        to: "to-pink-600",
        via: "via-pink-600",
        fromHover: "hover:from-pink-700",
        toHover: "hover:to-pink-700",
        viaHover: "hover:via-pink-700"
    },
    fuchsia: {
        base: "bg-fuchsia-600",
        baseHover: "hover:bg-fuchsia-600",
        baseChecked: "checked:bg-fuchsia-600",
        text: "text-fuchsia-600",
        textHover: "hover:text-fuchsia-700",
        hover: "hover:bg-fuchsia-700",
        muted: "bg-fuchsia-600/35",
        mutedHover: "hover:bg-fuchsia-700/35",
        subtle: "bg-fuchsia-600/10",
        subtleHover: "hover:bg-fuchsia-600/10",
        border: "border-fuchsia-600",
        borderHover: "hover:border-fuchsia-700",
        from: "from-fuchsia-600",
        to: "to-fuchsia-600",
        via: "via-fuchsia-600",
        fromHover: "hover:from-fuchsia-700",
        toHover: "hover:to-fuchsia-700",
        viaHover: "hover:via-fuchsia-700"
    },
    gray: {
        base: "bg-gray-600",
        baseHover: "hover:bg-gray-600",
        baseChecked: "checked:bg-gray-600",
        text: "text-gray-600",
        textHover: "hover:text-gray-700",
        hover: "hover:bg-gray-700",
        muted: "bg-gray-600/35",
        mutedHover: "hover:bg-gray-700/35",
        subtle: "bg-gray-600/10",
        subtleHover: "hover:bg-gray-600/10",
        border: "border-gray-600",
        borderHover: "hover:border-gray-700",
        from: "from-gray-600",
        to: "to-gray-600",
        via: "via-gray-600",
        fromHover: "hover:from-gray-700",
        toHover: "hover:to-gray-700",
        viaHover: "hover:via-gray-700"
    },
    sub: {
        base: "bg-sub-background",
        baseHover: "hover:bg-sub-background-hover",
        baseChecked: "checked:bg-sub-background-hover",
        text: "text-sub-background",
        textHover: "hover:text-sub-background-hover",
        hover: "hover:bg-sub-background-hover",
        muted: "bg-sub-background/35",
        mutedHover: "hover:bg-sub-background-hover/35",
        subtle: "bg-sub-background/10",
        subtleHover: "hover:bg-sub-background-hover/10",
        border: "border-sub-background",
        borderHover: "hover:border-sub-background-hover",
        from: "from-sub-background",
        to: "to-sub-background",
        via: "via-sub-background",
        fromHover: "hover:from-sub-background-hover",
        toHover: "hover:to-sub-background-hover",
        viaHover: "hover:via-sub-background-hover"
    },
    none: {
        base: "",
        baseHover: "",
        baseChecked: "",
        text: "",
        textHover: "",
        hover: "",
        muted: "",
        mutedHover: "",
        subtle: "",
        subtleHover: "",
        border: "",
        borderHover: "",
        from: "",
        to: "",
        via: "",
        fromHover: "",
        toHover: "",
        viaHover: ""
    },



    white: {
        base: "bg-white text-contrast-text",
        baseHover: "hover:bg-white",
        baseChecked: "checked:bg-white",
        textHover: "hover:text-contrast-text",
        hover: "hover:bg-gray-100",
        muted: "bg-gray-100/35",
        mutedHover: "hover:bg-gray-100/35",
        subtle: "bg-gray-100/10",
        subtleHover: "hover:bg-gray-100/10",
        border: "border-gray-100",
        borderHover: "hover:border-gray-300",
        text: "text-white",
        from: "from-white",
        to: "to-white",
        via: "via-white",
        fromHover: "hover:from-white",
        toHover: "hover:to-white",
        viaHover: "hover:via-white"
    },
    black: {
        base: "bg-black",
        baseHover: "hover:bg-black",
        baseChecked: "checked:bg-black",
        textHover: "hover:text-gray-300",
        hover: "hover:bg-black",
        muted: "bg-black/35",
        mutedHover: "hover:bg-black/35",
        subtle: "bg-black/10",
        subtleHover: "hover:bg-black/10",
        border: "border-black",
        borderHover: "hover:border-gray-700",
        text: "text-black",
        from: "from-black",
        to: "to-black",
        via: "via-black",
        fromHover: "hover:from-black",
        toHover: "hover:to-black",
        viaHover: "hover:via-black"
    },


    primary: {
        base: "bg-primary-600",
        baseHover: "hover:bg-primary-600",
        baseChecked: "checked:bg-primary-600",
        text: "text-primary-600",
        textHover: "hover:text-primary-700",
        hover: "hover:bg-primary-700",
        muted: "bg-primary-600/35",
        mutedHover: "hover:bg-primary-700/35",
        subtle: "bg-primary-600/10",
        subtleHover: "hover:bg-primary-700/10",
        border: "border-primary-600",
        borderHover: "hover:border-primary-700",
        from: "from-primary-600",
        to: "to-primary-600",
        via: "via-primary-600",
        fromHover: "hover:from-primary-700",
        toHover: "hover:to-primary-700",
        viaHover: "hover:via-primary-700"
    },
    secondary: {
        base: "bg-secondary-600",
        baseHover: "hover:bg-secondary-600",
        baseChecked: "checked:bg-secondary-600",
        text: "text-secondary-600",
        textHover: "hover:text-secondary-700",
        hover: "hover:bg-secondary-700",
        muted: "bg-secondary-600/35",
        mutedHover: "hover:bg-secondary-700/35",
        subtle: "bg-secondary-600/10",
        subtleHover: "hover:bg-secondary-700/10",
        border: "border-secondary-600",
        borderHover: "hover:border-secondary-700",
        from: "from-secondary-600",
        to: "to-secondary-600",
        via: "via-secondary-600",
        fromHover: "hover:from-secondary-700",
        toHover: "hover:to-secondary-700",
        viaHover: "hover:via-secondary-700"
    },
    accent: {
        base: "bg-accent-600",
        baseHover: "hover:bg-accent-600",
        baseChecked: "checked:bg-accent-600",
        text: "text-accent-600",
        textHover: "hover:text-accent-700",
        hover: "hover:bg-accent-700",
        muted: "bg-accent-600/35",
        mutedHover: "hover:bg-accent-700/35",
        subtle: "bg-accent-600/10",
        subtleHover: "hover:bg-accent-700/10",
        border: "border-accent-600",
        borderHover: "hover:border-accent-700",
        from: "from-accent-600",
        to: "to-accent-600",
        via: "via-accent-600",
        fromHover: "hover:from-accent-700",
        toHover: "hover:to-accent-700",
        viaHover: "hover:via-accent-700"
    },


    error: {
        base: "bg-red-600",
        baseHover: "hover:bg-red-600",
        baseChecked: "checked:bg-red-600",
        text: "text-red-600",
        textHover: "hover:text-red-700",
        hover: "hover:bg-red-700",
        muted: "bg-red-600/35",
        mutedHover: "hover:bg-red-700/35",
        subtle: "bg-red-600/10",
        subtleHover: "hover:bg-red-600/10",
        border: "border-red-600",
        borderHover: "hover:border-red-700",
        from: "from-red-600",
        to: "to-red-600",
        via: "via-red-600",
        fromHover: "hover:from-red-700",
        toHover: "hover:to-red-700",
        viaHover: "hover:via-red-700"
    },
    warning: {
        base: "bg-amber-600",
        baseHover: "hover:bg-amber-600",
        baseChecked: "checked:bg-amber-600",
        text: "text-amber-600",
        textHover: "hover:text-amber-700",
        hover: "hover:bg-amber-700",
        muted: "bg-amber-600/35",
        mutedHover: "hover:bg-amber-700/35",
        subtle: "bg-amber-600/10",
        subtleHover: "hover:bg-amber-600/10",
        border: "border-amber-600",
        borderHover: "hover:border-amber-700",
        from: "from-amber-600",
        to: "to-amber-600",
        via: "via-amber-600",
        fromHover: "hover:from-amber-700",
        toHover: "hover:to-amber-700",
        viaHover: "hover:via-amber-700"
    },
    success: {
        base: "bg-emerald-600",
        baseHover: "hover:bg-emerald-600",
        baseChecked: "checked:bg-emerald-600",
        textHover: "hover:text-emerald-700",
        hover: "hover:bg-emerald-700",
        muted: "bg-emerald-600/35",
        mutedHover: "hover:bg-emerald-700/35",
        subtle: "bg-emerald-600/10",
        subtleHover: "hover:bg-emerald-600/10",
        border: "border-emerald-600",
        borderHover: "hover:border-emerald-700",
        text: "text-emerald-600",
        from: "from-emerald-600",
        to: "to-emerald-600",
        via: "via-emerald-600",
        fromHover: "hover:from-emerald-700",
        toHover: "hover:to-emerald-700",
        viaHover: "hover:via-emerald-700"
    },
    info: {
        base: "bg-sky-600",
        baseHover: "hover:bg-sky-600",
        baseChecked: "checked:bg-sky-600",
        text: "text-sky-600",
        textHover: "hover:text-sky-700",
        hover: "hover:bg-sky-700",
        muted: "bg-sky-600/35",
        mutedHover: "hover:bg-sky-700/35",
        subtle: "bg-sky-600/10",
        subtleHover: "hover:bg-sky-600/10",
        border: "border-sky-600",
        borderHover: "hover:border-sky-700",
        from: "from-sky-600",
        to: "to-sky-600",
        via: "via-sky-600",
        fromHover: "hover:from-sky-700",
        toHover: "hover:to-sky-700",
        viaHover: "hover:via-sky-700"
    }
}

export function generateColorStyle(color: Color, variant: ColorStyleType) {
    const styles = colorStyleParts[color];
    if (!styles) return "";
    return styles[variant] || "";
}

export function getColorClasses(color: ColorType, variant: string, hoverValues: boolean, valueCallback: (color: Color, variant: any) => string) {
    if (typeof color === "string")
        return valueCallback(color, variant);
    else {
        const from = colorStyleParts[color.from].from;
        const to = colorStyleParts[color.to].to;
        const via = color.via ? colorStyleParts[color.via].via : "";
        const fromHover = colorStyleParts[color.from].fromHover;
        const toHover = colorStyleParts[color.to].toHover;
        const viaHover = color.via ? colorStyleParts[color.via].viaHover : "";
        return `${from} ${to} ${via} ${ hoverValues ? `${fromHover} ${toHover} ${viaHover}` : "" }`.trim();
    }
}

export function getGradientStyle(color: ColorType) {
    return typeof color === "object"
        ? `background-image: linear-gradient(${color.deg || 90}deg, var(--tw-gradient-from), ${color.via ? `var(--tw-gradient-via), ` : ``}var(--tw-gradient-to))`
        : "";
}